# -------------------------------------------------------
# Railway deployment configuration for ProxiPro
# https://docs.railway.app/reference/config-as-code
# -------------------------------------------------------

[build]

[deploy]
healthcheckPath = "/health.php"
healthcheckTimeout = 600
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
numReplicas = 1
