<?php

return [
    'default_domain' => 'service',

    'category_domains' => [
        'Covoiturage' => 'ridesharing',
        'Vente' => 'sale',
        'Emploi' => 'employment',
        'Location' => 'rental',
        'Perdu/disparu' => 'lost_found',
    ],

    'domains' => [
        'service' => [
            'label' => 'Prestation de service',
            'icon' => '🛠️',
            'introduction' => 'Précisez comment et quand la prestation peut être réalisée.',
            'title_placeholders' => [
                'demande' => 'Ex : Recherche plombier pour une fuite urgente',
                'offre' => 'Ex : Plombier disponible pour vos dépannages',
            ],
            'description_placeholders' => [
                'demande' => 'Décrivez le besoin, le délai souhaité, les contraintes et le résultat attendu…',
                'offre' => 'Présentez la prestation, votre expérience, vos disponibilités et vos conditions…',
            ],
            'price' => [
                'title' => 'Tarification',
                'mode_label' => 'Mode de tarification',
                'allowed_types' => ['fixed', 'hourly', 'negotiable'],
                'default_type' => 'negotiable',
                'type_labels' => [
                    'fixed' => 'Prix global',
                    'hourly' => 'Tarif horaire',
                    'negotiable' => 'À négocier',
                ],
                'amount_labels' => ['fixed' => 'Prix global', 'hourly' => 'Tarif horaire'],
                'suffixes' => ['fixed' => '€', 'hourly' => '€/h'],
                'hint' => 'Indiquez un tarif clair ou choisissez « À négocier ».',
            ],
            'location' => ['title' => 'Zone de prestation', 'show_radius' => true],
            'fields' => [
                'intervention_mode' => [
                    'label' => 'Mode d’intervention',
                    'type' => 'select',
                    'placeholder' => 'Sélectionner un mode',
                    'options' => [
                        'customer_location' => 'Chez le client',
                        'provider_location' => 'Chez le prestataire',
                        'remote' => 'À distance',
                        'flexible' => 'Selon le besoin',
                    ],
                    'rules' => ['nullable', 'string', 'in:customer_location,provider_location,remote,flexible'],
                ],
                'availability' => [
                    'label' => 'Disponibilité',
                    'type' => 'select',
                    'placeholder' => 'Sélectionner une disponibilité',
                    'options' => [
                        'immediate' => 'Immédiatement',
                        'this_week' => 'Cette semaine',
                        'weekdays' => 'En semaine',
                        'weekends' => 'Le week-end',
                        'appointment' => 'Sur rendez-vous',
                    ],
                    'rules' => ['nullable', 'string', 'in:immediate,this_week,weekdays,weekends,appointment'],
                ],
                'estimated_duration' => [
                    'label' => 'Durée estimée',
                    'type' => 'text',
                    'placeholder' => 'Ex : 2 heures, 3 jours',
                    'maxlength' => 80,
                    'rules' => ['nullable', 'string', 'max:80'],
                ],
            ],
        ],

        'employment' => [
            'label' => 'Emploi',
            'icon' => '💼',
            'introduction' => 'Ajoutez les conditions essentielles pour permettre aux candidats ou recruteurs de se positionner rapidement.',
            'title_placeholders' => [
                'demande' => 'Ex : Développeur web recherche un CDI à Lyon',
                'offre' => 'Ex : Nous recrutons un technicien de maintenance',
            ],
            'description_placeholders' => [
                'demande' => 'Présentez vos compétences, votre expérience, votre mobilité et vos disponibilités…',
                'offre' => 'Décrivez les missions, le profil recherché, les avantages et le processus de candidature…',
            ],
            'price' => [
                'title' => 'Rémunération',
                'mode_label' => 'Présentation de la rémunération',
                'allowed_types' => ['fixed', 'hourly', 'negotiable'],
                'default_type' => 'negotiable',
                'type_labels' => [
                    'fixed' => 'Salaire annoncé',
                    'hourly' => 'Taux horaire',
                    'negotiable' => 'Selon profil',
                ],
                'amount_labels' => ['fixed' => 'Rémunération', 'hourly' => 'Taux horaire'],
                'suffixes' => ['fixed' => '€', 'hourly' => '€/h'],
                'hint' => 'Indiquez une rémunération réaliste et précisez sa périodicité.',
            ],
            'location' => ['title' => 'Lieu de travail ou zone recherchée', 'show_radius' => false],
            'fields' => [
                'work_mode' => [
                    'label' => 'Mode de travail',
                    'type' => 'select',
                    'required' => true,
                    'placeholder' => 'Sélectionner un mode',
                    'options' => ['on_site' => 'Sur site', 'hybrid' => 'Hybride', 'remote' => 'Télétravail'],
                    'rules' => ['required', 'string', 'in:on_site,hybrid,remote'],
                ],
                'work_time' => [
                    'label' => 'Temps de travail',
                    'type' => 'select',
                    'required' => true,
                    'placeholder' => 'Sélectionner un rythme',
                    'options' => ['full_time' => 'Temps plein', 'part_time' => 'Temps partiel', 'flexible' => 'Horaires flexibles'],
                    'rules' => ['required', 'string', 'in:full_time,part_time,flexible'],
                ],
                'experience_level' => [
                    'label' => 'Niveau d’expérience',
                    'type' => 'select',
                    'required' => true,
                    'placeholder' => 'Sélectionner un niveau',
                    'options' => [
                        'beginner' => 'Débutant accepté',
                        'junior' => 'Junior (1–2 ans)',
                        'confirmed' => 'Confirmé (3–5 ans)',
                        'senior' => 'Senior (6 ans et plus)',
                    ],
                    'rules' => ['required', 'string', 'in:beginner,junior,confirmed,senior'],
                ],
                'compensation_period' => [
                    'label' => 'Période de rémunération',
                    'type' => 'select',
                    'required' => true,
                    'placeholder' => 'Sélectionner une période',
                    'options' => ['hour' => 'Par heure', 'day' => 'Par jour', 'month' => 'Par mois', 'year' => 'Par an'],
                    'rules' => ['required', 'string', 'in:hour,day,month,year'],
                ],
                'start_date' => [
                    'label' => 'Date de début souhaitée',
                    'type' => 'date',
                    'rules' => ['nullable', 'date', 'after_or_equal:today'],
                ],
                'application_deadline' => [
                    'label' => 'Date limite de candidature',
                    'type' => 'date',
                    'rules' => ['nullable', 'date', 'after_or_equal:today'],
                ],
            ],
        ],

        'ridesharing' => [
            'label' => 'Covoiturage',
            'icon' => '🚗',
            'introduction' => 'Renseignez le trajet et l’horaire exacts afin que les voyageurs puissent comparer les offres.',
            'title_placeholders' => [
                'demande' => 'Ex : Recherche une place Paris → Lille vendredi',
                'offre' => 'Ex : 3 places Paris → Lille vendredi à 18 h',
            ],
            'description_placeholders' => [
                'demande' => 'Précisez vos contraintes horaires, vos bagages et le point de rendez-vous souhaité…',
                'offre' => 'Précisez les étapes, le véhicule, les bagages acceptés et les conditions du trajet…',
            ],
            'price' => [
                'title' => 'Participation au trajet',
                'mode_label' => 'Prix par place',
                'allowed_types' => ['fixed', 'negotiable'],
                'default_type' => 'fixed',
                'type_labels' => ['fixed' => 'Prix par place', 'negotiable' => 'À convenir'],
                'amount_labels' => ['fixed' => 'Prix par place'],
                'suffixes' => ['fixed' => '€/place'],
                'hint' => 'Le montant indiqué correspond à une place pour ce trajet.',
            ],
            'location' => ['title' => 'Zone de départ de l’annonce', 'show_radius' => false],
            'fields' => [
                'departure' => [
                    'label' => 'Lieu de départ',
                    'type' => 'text',
                    'required' => true,
                    'placeholder' => 'Ville, quartier ou point de rendez-vous',
                    'maxlength' => 160,
                    'rules' => ['required', 'string', 'max:160', 'different:ad_details.destination'],
                ],
                'destination' => [
                    'label' => 'Destination',
                    'type' => 'text',
                    'required' => true,
                    'placeholder' => 'Ville ou destination finale',
                    'maxlength' => 160,
                    'rules' => ['required', 'string', 'max:160', 'different:ad_details.departure'],
                ],
                'departure_at' => [
                    'label' => 'Départ prévu',
                    'type' => 'datetime-local',
                    'required' => true,
                    'rules' => ['required', 'date', 'after:now'],
                ],
                'available_seats' => [
                    'label' => 'Nombre de places',
                    'type' => 'number',
                    'required' => true,
                    'min' => 1,
                    'max' => 8,
                    'step' => 1,
                    'rules' => ['required', 'integer', 'min:1', 'max:8'],
                ],
                'trip_type' => [
                    'label' => 'Type de trajet',
                    'type' => 'select',
                    'required' => true,
                    'options' => ['one_way' => 'Aller simple', 'round_trip' => 'Aller-retour'],
                    'rules' => ['required', 'string', 'in:one_way,round_trip'],
                ],
                'return_at' => [
                    'label' => 'Retour prévu',
                    'type' => 'datetime-local',
                    'show_when' => ['trip_type' => 'round_trip'],
                    'required_when' => ['trip_type' => 'round_trip'],
                    'rules' => ['nullable', 'required_if:ad_details.trip_type,round_trip', 'date', 'after:ad_details.departure_at'],
                ],
                'luggage' => [
                    'label' => 'Bagages acceptés',
                    'type' => 'select',
                    'options' => ['none' => 'Sans bagage', 'small' => 'Petit bagage', 'large' => 'Gros bagage'],
                    'rules' => ['nullable', 'string', 'in:none,small,large'],
                ],
            ],
        ],

        'sale' => [
            'label' => 'Vente',
            'icon' => '🛒',
            'introduction' => 'Décrivez précisément l’état du bien et les modalités de remise pour rassurer les acheteurs.',
            'title_placeholders' => [
                'demande' => 'Ex : Recherche iPhone 15 en très bon état',
                'offre' => 'Ex : iPhone 15 128 Go en excellent état',
            ],
            'description_placeholders' => [
                'demande' => 'Indiquez le modèle recherché, l’état accepté, votre budget et les critères indispensables…',
                'offre' => 'Décrivez l’état réel, les défauts éventuels, les accessoires, la facture et la garantie…',
            ],
            'price' => [
                'title' => 'Prix de vente',
                'mode_label' => 'Prix demandé ou budget',
                'allowed_types' => ['fixed', 'negotiable'],
                'default_type' => 'fixed',
                'type_labels' => ['fixed' => 'Prix de vente', 'negotiable' => 'Prix à négocier'],
                'amount_labels' => ['fixed' => 'Prix de vente'],
                'suffixes' => ['fixed' => '€'],
                'hint' => 'Affichez un prix cohérent avec l’état et le marché.',
            ],
            'location' => ['title' => 'Lieu de remise ou de vente', 'show_radius' => false],
            'fields' => [
                'condition' => [
                    'label' => 'État du bien',
                    'type' => 'select',
                    'required' => true,
                    'placeholder' => 'Sélectionner un état',
                    'options' => [
                        'new' => 'Neuf',
                        'like_new' => 'Comme neuf',
                        'good' => 'Bon état',
                        'fair' => 'État correct',
                        'for_parts' => 'Pour pièces / à réparer',
                    ],
                    'rules' => ['required', 'string', 'in:new,like_new,good,fair,for_parts'],
                ],
                'delivery_method' => [
                    'label' => 'Mode de remise',
                    'type' => 'select',
                    'required' => true,
                    'options' => ['pickup' => 'Remise en main propre', 'shipping' => 'Expédition', 'both' => 'Les deux'],
                    'rules' => ['required', 'string', 'in:pickup,shipping,both'],
                ],
                'brand' => [
                    'label' => 'Marque',
                    'type' => 'text',
                    'placeholder' => 'Ex : Apple, Renault, IKEA',
                    'maxlength' => 100,
                    'rules' => ['nullable', 'string', 'max:100'],
                ],
                'model' => [
                    'label' => 'Modèle / référence',
                    'type' => 'text',
                    'placeholder' => 'Ex : iPhone 15, Clio V',
                    'maxlength' => 120,
                    'rules' => ['nullable', 'string', 'max:120'],
                ],
                'quantity' => [
                    'label' => 'Quantité disponible',
                    'type' => 'number',
                    'min' => 1,
                    'max' => 999,
                    'step' => 1,
                    'default' => 1,
                    'rules' => ['nullable', 'integer', 'min:1', 'max:999'],
                ],
            ],
        ],

        'rental' => [
            'label' => 'Location',
            'icon' => '🔑',
            'introduction' => 'Indiquez la période, la disponibilité et les frais annexes pour éviter les demandes incomplètes.',
            'title_placeholders' => [
                'demande' => 'Ex : Recherche utilitaire à louer pour le week-end',
                'offre' => 'Ex : Utilitaire 12 m³ disponible à la journée',
            ],
            'description_placeholders' => [
                'demande' => 'Précisez les dates, la durée, l’usage prévu et les contraintes indispensables…',
                'offre' => 'Décrivez le bien, les conditions de location, l’assurance, la caution et les restrictions…',
            ],
            'price' => [
                'title' => 'Tarif de location',
                'mode_label' => 'Tarif de référence',
                'allowed_types' => ['fixed', 'negotiable'],
                'default_type' => 'fixed',
                'type_labels' => ['fixed' => 'Tarif de location', 'negotiable' => 'Sur devis'],
                'amount_labels' => ['fixed' => 'Tarif de location'],
                'suffixes' => ['fixed' => '€'],
                'hint' => 'Le tarif sera présenté avec la période choisie ci-dessus.',
            ],
            'location' => ['title' => 'Lieu de retrait ou du bien', 'show_radius' => false],
            'fields' => [
                'rental_period' => [
                    'label' => 'Unité de location',
                    'type' => 'select',
                    'required' => true,
                    'placeholder' => 'Sélectionner une période',
                    'options' => ['hour' => 'Par heure', 'day' => 'Par jour', 'week' => 'Par semaine', 'month' => 'Par mois'],
                    'rules' => ['required', 'string', 'in:hour,day,week,month'],
                ],
                'availability_from' => [
                    'label' => 'Disponible à partir du',
                    'type' => 'date',
                    'required' => true,
                    'rules' => ['required', 'date', 'after_or_equal:today'],
                ],
                'availability_to' => [
                    'label' => 'Disponible jusqu’au',
                    'type' => 'date',
                    'rules' => ['nullable', 'date', 'after_or_equal:ad_details.availability_from'],
                ],
                'minimum_duration' => [
                    'label' => 'Durée minimale',
                    'type' => 'number',
                    'min' => 1,
                    'max' => 365,
                    'step' => 1,
                    'placeholder' => 'Ex : 2',
                    'rules' => ['nullable', 'integer', 'min:1', 'max:365'],
                ],
                'deposit' => [
                    'label' => 'Caution demandée (€)',
                    'type' => 'number',
                    'min' => 0,
                    'max' => 1000000,
                    'step' => 0.01,
                    'rules' => ['nullable', 'numeric', 'min:0', 'max:1000000'],
                ],
            ],
        ],

        'lost_found' => [
            'label' => 'Perdu, trouvé ou disparu',
            'icon' => '🔍',
            'introduction' => 'Donnez des repères factuels, sans publier d’information personnelle sensible.',
            'title_placeholders' => [
                'demande' => 'Ex : Clés perdues près de la gare mardi',
                'offre' => 'Ex : Trousseau de clés trouvé près de la gare',
            ],
            'description_placeholders' => [
                'demande' => 'Décrivez l’objet, l’animal ou la situation et les circonstances utiles à l’identification…',
                'offre' => 'Décrivez ce qui a été trouvé sans révéler tous les signes distinctifs permettant de vérifier le propriétaire…',
            ],
            'price' => [
                'title' => 'Récompense éventuelle',
                'mode_label' => 'Récompense',
                'allowed_types' => ['fixed', 'negotiable'],
                'default_type' => 'negotiable',
                'type_labels' => ['fixed' => 'Montant proposé', 'negotiable' => 'Aucune récompense annoncée'],
                'amount_labels' => ['fixed' => 'Montant de la récompense'],
                'suffixes' => ['fixed' => '€'],
                'hint' => 'La récompense est facultative et ne doit jamais conditionner la restitution d’un document officiel.',
            ],
            'location' => ['title' => 'Dernier lieu connu ou lieu de découverte', 'show_radius' => false],
            'fields' => [
                'incident_type' => [
                    'label' => 'Nature du signalement',
                    'type' => 'select',
                    'required' => true,
                    'options' => ['lost' => 'Perdu', 'found' => 'Trouvé', 'stolen' => 'Volé', 'missing' => 'Disparu'],
                    'rules' => ['required', 'string', 'in:lost,found,stolen,missing'],
                ],
                'incident_date' => [
                    'label' => 'Date de l’événement',
                    'type' => 'date',
                    'required' => true,
                    'rules' => ['required', 'date', 'before_or_equal:today'],
                ],
                'distinctive_signs' => [
                    'label' => 'Signes distinctifs',
                    'type' => 'text',
                    'placeholder' => 'Couleur, taille, détail visible…',
                    'maxlength' => 180,
                    'rules' => ['nullable', 'string', 'max:180'],
                ],
                'reference_number' => [
                    'label' => 'Référence de déclaration',
                    'type' => 'text',
                    'placeholder' => 'Facultatif — ne publiez aucun numéro sensible',
                    'maxlength' => 80,
                    'rules' => ['nullable', 'string', 'max:80'],
                ],
            ],
        ],
    ],
];
