<?php

return [
    'countries' => [
        'France' => '🇫🇷',
        'Guadeloupe' => '🇬🇵',
        'Martinique' => '🇲🇶',
        'Guyane' => '🇬🇫',
        'La Réunion' => '🇷🇪',
        'Mayotte' => '🇾🇹',
        'Allemagne' => '🇩🇪',
        'Autriche' => '🇦🇹',
        'Belgique' => '🇧🇪',
        'Bulgarie' => '🇧🇬',
        'Chypre' => '🇨🇾',
        'Croatie' => '🇭🇷',
        'Espagne' => '🇪🇸',
        'Estonie' => '🇪🇪',
        'Finlande' => '🇫🇮',
        'Grèce' => '🇬🇷',
        'Irlande' => '🇮🇪',
        'Italie' => '🇮🇹',
        'Lettonie' => '🇱🇻',
        'Lituanie' => '🇱🇹',
        'Luxembourg' => '🇱🇺',
        'Malte' => '🇲🇹',
        'Pays-Bas' => '🇳🇱',
        'Portugal' => '🇵🇹',
        'Slovaquie' => '🇸🇰',
        'Slovénie' => '🇸🇮',
        'Monaco' => '🇲🇨',
        'Suisse' => '🇨🇭',
        'Algérie' => '🇩🇿',
        'Bénin' => '🇧🇯',
        'Burkina Faso' => '🇧🇫',
        'Burundi' => '🇧🇮',
        'Cameroun' => '🇨🇲',
        'Comores' => '🇰🇲',
        'Côte d\'Ivoire' => '🇨🇮',
        'Djibouti' => '🇩🇯',
        'Gabon' => '🇬🇦',
        'Guinée' => '🇬🇳',
        'Guinée équatoriale' => '🇬🇶',
        'Madagascar' => '🇲🇬',
        'Mali' => '🇲🇱',
        'Maroc' => '🇲🇦',
        'Maurice' => '🇲🇺',
        'Mauritanie' => '🇲🇷',
        'Niger' => '🇳🇪',
        'République centrafricaine' => '🇨🇫',
        'République démocratique du Congo' => '🇨🇩',
        'République du Congo' => '🇨🇬',
        'Rwanda' => '🇷🇼',
        'Sénégal' => '🇸🇳',
        'Seychelles' => '🇸🇨',
        'Tchad' => '🇹🇩',
        'Togo' => '🇹🇬',
        'Tunisie' => '🇹🇳',
        'Canada' => '🇨🇦',
    ],

    'cities' => [
        'France' => [
            'Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg',
            'Montpellier', 'Bordeaux', 'Lille', 'Rennes', 'Reims', 'Le Havre',
            'Saint-Étienne', 'Toulon', 'Grenoble', 'Dijon', 'Angers', 'Nîmes',
            'Villeurbanne', 'Clermont-Ferrand', 'Le Mans', 'Aix-en-Provence', 'Brest',
            'Tours', 'Amiens', 'Limoges', 'Perpignan', 'Metz', 'Besançon', 'Orléans',
            'Rouen', 'Mulhouse', 'Caen', 'Nancy', 'Argenteuil', 'Saint-Denis',
            'Montreuil', 'Roubaix', 'Avignon',
        ],
        'Guadeloupe' => [
            'Les Abymes', 'Baie-Mahault', 'Le Gosier', 'Petit-Bourg', 'Sainte-Anne',
            'Le Moule', 'Capesterre-Belle-Eau', 'Pointe-à-Pitre', 'Basse-Terre',
            'Sainte-Rose', 'Morne-à-l\'Eau', 'Saint-François',
        ],
        'Martinique' => [
            'Fort-de-France', 'Le Lamentin', 'Le Robert', 'Schoelcher', 'Le François',
            'Sainte-Marie', 'Ducos', 'Rivière-Pilote', 'La Trinité', 'Saint-Joseph',
            'Le Marin', 'Les Trois-Îlets',
        ],
        'Guyane' => [
            'Cayenne', 'Saint-Laurent-du-Maroni', 'Matoury', 'Kourou', 'Remire-Montjoly',
            'Macouria', 'Mana', 'Maripasoula', 'Apatou', 'Grand-Santi', 'Sinnamary',
            'Roura',
        ],
        'La Réunion' => [
            'Saint-Denis', 'Saint-Paul', 'Saint-Pierre', 'Le Tampon', 'Saint-André',
            'Saint-Louis', 'Saint-Benoît', 'Le Port', 'Saint-Joseph', 'Sainte-Marie',
            'Sainte-Suzanne', 'Saint-Leu', 'La Possession', 'Bras-Panon', 'Cilaos',
            'Salazie',
        ],
        'Mayotte' => [
            'Mamoudzou', 'Koungou', 'Dzaoudzi', 'Dembeni', 'Bandraboua', 'Tsingoni',
            'Sada', 'Ouangani', 'Chiconi', 'Pamandzi', 'Mtsamboro', 'Acoua',
            'Chirongui', 'Bouéni', 'Kani-Kéli', 'Bandrélé', 'M\'Tsangamouji',
        ],
        'Allemagne' => ['Berlin', 'Hambourg', 'Munich', 'Cologne', 'Francfort', 'Stuttgart', 'Düsseldorf', 'Dortmund', 'Essen', 'Leipzig'],
        'Autriche' => ['Vienne', 'Graz', 'Linz', 'Salzbourg', 'Innsbruck', 'Klagenfurt', 'Villach', 'Wels', 'Sankt Pölten'],
        'Belgique' => ['Bruxelles', 'Anvers', 'Gand', 'Charleroi', 'Liège', 'Bruges', 'Namur', 'Louvain', 'Mons', 'Alost', 'Malines', 'La Louvière', 'Courtrai', 'Ostende', 'Hasselt'],
        'Bulgarie' => ['Sofia', 'Plovdiv', 'Varna', 'Bourgas', 'Roussé', 'Stara Zagora', 'Pleven', 'Sliven', 'Dobritch', 'Choumen'],
        'Chypre' => ['Nicosie', 'Limassol', 'Larnaca', 'Paphos', 'Famagouste', 'Kyrenia', 'Protaras'],
        'Croatie' => ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar', 'Pula', 'Slavonski Brod', 'Karlovac', 'Varaždin', 'Šibenik'],
        'Espagne' => ['Madrid', 'Barcelone', 'Valence', 'Séville', 'Saragosse', 'Malaga', 'Murcie', 'Palma', 'Bilbao', 'Alicante'],
        'Estonie' => ['Tallinn', 'Tartu', 'Narva', 'Pärnu', 'Kohtla-Järve', 'Viljandi', 'Rakvere'],
        'Finlande' => ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu', 'Turku', 'Jyväskylä', 'Lahti', 'Kuopio'],
        'Grèce' => ['Athènes', 'Thessalonique', 'Patras', 'Héraklion', 'Larissa', 'Volos', 'Ioannina', 'La Canée', 'Rhodes'],
        'Irlande' => ['Dublin', 'Cork', 'Galway', 'Limerick', 'Waterford', 'Drogheda', 'Dundalk', 'Sligo', 'Kilkenny'],
        'Italie' => ['Rome', 'Milan', 'Naples', 'Turin', 'Palerme', 'Gênes', 'Bologne', 'Florence', 'Bari', 'Catane'],
        'Lettonie' => ['Riga', 'Daugavpils', 'Liepāja', 'Jelgava', 'Jūrmala', 'Ventspils', 'Rēzekne', 'Valmiera'],
        'Lituanie' => ['Vilnius', 'Kaunas', 'Klaipėda', 'Šiauliai', 'Panevėžys', 'Alytus', 'Marijampolė'],
        'Luxembourg' => ['Luxembourg', 'Esch-sur-Alzette', 'Differdange', 'Dudelange', 'Ettelbruck', 'Diekirch', 'Wiltz', 'Echternach'],
        'Malte' => ['La Valette', 'Birkirkara', 'Mosta', 'Qormi', 'Sliema', 'Saint Paul\'s Bay', 'Żabbar', 'San Ġwann'],
        'Pays-Bas' => ['Amsterdam', 'Rotterdam', 'La Haye', 'Utrecht', 'Eindhoven', 'Tilbourg', 'Groningue', 'Almere', 'Breda', 'Nimègue'],
        'Portugal' => ['Lisbonne', 'Porto', 'Vila Nova de Gaia', 'Amadora', 'Braga', 'Coimbra', 'Funchal', 'Setúbal', 'Faro'],
        'Slovaquie' => ['Bratislava', 'Košice', 'Prešov', 'Žilina', 'Nitra', 'Banská Bystrica', 'Trnava', 'Martin'],
        'Slovénie' => ['Ljubljana', 'Maribor', 'Celje', 'Kranj', 'Koper', 'Velenje', 'Novo Mesto', 'Ptuj'],
        'Monaco' => ['Monaco', 'Monte-Carlo', 'La Condamine', 'Fontvieille', 'Moneghetti'],
        'Suisse' => ['Zurich', 'Genève', 'Bâle', 'Lausanne', 'Berne', 'Winterthour', 'Lucerne', 'Saint-Gall', 'Lugano', 'Bienne', 'Fribourg', 'Neuchâtel', 'Sion'],
        'Algérie' => ['Alger', 'Oran', 'Constantine', 'Annaba', 'Blida', 'Batna', 'Sétif', 'Djelfa', 'Sidi Bel Abbès', 'Biskra', 'Tébessa', 'Skikda', 'Tiaret', 'Béjaïa', 'Tlemcen', 'Ouargla'],
        'Bénin' => ['Cotonou', 'Porto-Novo', 'Parakou', 'Abomey-Calavi', 'Djougou', 'Bohicon', 'Kandi', 'Natitingou', 'Lokossa'],
        'Burkina Faso' => ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou', 'Ouahigouya', 'Banfora', 'Kaya', 'Dédougou', 'Tenkodogo', 'Fada N\'Gourma'],
        'Burundi' => ['Bujumbura', 'Gitega', 'Ngozi', 'Rumonge', 'Muyinga', 'Ruyigi', 'Bururi', 'Kayanza'],
        'Cameroun' => ['Douala', 'Yaoundé', 'Garoua', 'Bamenda', 'Maroua', 'Bafoussam', 'Ngaoundéré', 'Bertoua', 'Limbe', 'Kribi', 'Ebolowa', 'Buea'],
        'Comores' => ['Moroni', 'Mutsamudu', 'Fomboni', 'Domoni', 'Ouani', 'Mitsamiouli', 'Iconi'],
        'Côte d\'Ivoire' => ['Abidjan', 'Bouaké', 'Yamoussoukro', 'Korhogo', 'San-Pédro', 'Man', 'Divo', 'Daloa', 'Gagnoa', 'Abengourou', 'Anyama', 'Agboville', 'Dabou', 'Grand-Bassam', 'Bingerville'],
        'Djibouti' => ['Djibouti', 'Ali Sabieh', 'Tadjourah', 'Dikhil', 'Obock', 'Arta'],
        'Gabon' => ['Libreville', 'Port-Gentil', 'Franceville', 'Oyem', 'Moanda', 'Mouila', 'Lambaréné', 'Tchibanga'],
        'Guinée' => ['Conakry', 'Kankan', 'Nzérékoré', 'Kindia', 'Labé', 'Mamou', 'Boké', 'Faranah'],
        'Guinée équatoriale' => ['Malabo', 'Bata', 'Ebebiyín', 'Aconibe', 'Añisoc', 'Luba', 'Evinayong'],
        'Madagascar' => ['Antananarivo', 'Toamasina', 'Antsirabe', 'Fianarantsoa', 'Mahajanga', 'Toliara', 'Antsiranana', 'Ambatondrazaka', 'Antalaha', 'Nosy Be', 'Sainte-Marie', 'Morondava', 'Ambositra', 'Mananjary', 'Sambava'],
        'Mali' => ['Bamako', 'Sikasso', 'Ségou', 'Mopti', 'Koutiala', 'Kayes', 'Gao', 'Tombouctou', 'Kati'],
        'Maroc' => ['Casablanca', 'Rabat', 'Fès', 'Marrakech', 'Tanger', 'Agadir', 'Meknès', 'Oujda', 'Kénitra', 'Tétouan', 'Safi', 'El Jadida', 'Nador', 'Béni Mellal', 'Essaouira', 'Ouarzazate'],
        'Maurice' => ['Port-Louis', 'Beau Bassin-Rose Hill', 'Vacoas-Phoenix', 'Curepipe', 'Quatre Bornes', 'Triolet', 'Goodlands', 'Centre de Flacq', 'Mahébourg', 'Grand Baie', 'Flic en Flac', 'Tamarin'],
        'Mauritanie' => ['Nouakchott', 'Nouadhibou', 'Kiffa', 'Kaédi', 'Rosso', 'Zouérate', 'Atar', 'Sélibabi'],
        'Niger' => ['Niamey', 'Zinder', 'Maradi', 'Agadez', 'Tahoua', 'Dosso', 'Diffa', 'Tillabéri'],
        'République centrafricaine' => ['Bangui', 'Bimbo', 'Berbérati', 'Carnot', 'Bambari', 'Bouar', 'Bossangoa', 'Bria'],
        'République démocratique du Congo' => ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kisangani', 'Kananga', 'Goma', 'Bukavu', 'Kolwezi', 'Likasi', 'Matadi'],
        'République du Congo' => ['Brazzaville', 'Pointe-Noire', 'Dolisie', 'Nkayi', 'Owando', 'Ouesso', 'Madingou', 'Kinkala'],
        'Rwanda' => ['Kigali', 'Butare', 'Gitarama', 'Ruhengeri', 'Gisenyi', 'Byumba', 'Cyangugu', 'Kibuye'],
        'Sénégal' => ['Dakar', 'Thiès', 'Rufisque', 'Kaolack', 'M\'Bour', 'Saint-Louis', 'Ziguinchor', 'Diourbel', 'Louga', 'Tambacounda', 'Kolda', 'Richard-Toll', 'Tivaouane', 'Touba', 'Kédougou'],
        'Seychelles' => ['Victoria', 'Anse Boileau', 'Beau Vallon', 'Cascade', 'Takamaka', 'Anse Royale'],
        'Tchad' => ['N\'Djamena', 'Moundou', 'Sarh', 'Abéché', 'Kélo', 'Koumra', 'Pala', 'Bongor'],
        'Togo' => ['Lomé', 'Sokodé', 'Kara', 'Kpalimé', 'Atakpamé', 'Bassar', 'Tsévié', 'Aného'],
        'Tunisie' => ['Tunis', 'Sfax', 'Sousse', 'Kairouan', 'Bizerte', 'Gabès', 'Ariana', 'Gafsa', 'El Mourouj', 'Kasserine', 'Monastir', 'La Marsa', 'Hammamet', 'Djerba', 'Tozeur'],
        'Canada' => ['Toronto', 'Montréal', 'Vancouver', 'Calgary', 'Edmonton', 'Ottawa', 'Winnipeg', 'Québec', 'Hamilton', 'Kitchener', 'London', 'Victoria', 'Halifax', 'Oshawa', 'Windsor', 'Saskatoon', 'Regina', 'Sherbrooke', 'Laval', 'Gatineau'],
    ],
];
